import type { Metadata, Viewport } from 'next'
import { unstable_ViewTransition as ViewTransition } from 'react'

import cn from 'clsx'
// import localFont from 'next/font/local'
import 'katex/dist/katex.min.css'


import './globals.css'
import Navbar from '@/components/Navbar'
import { Provider } from 'react-wrap-balancer'
import { ModeToggle } from '@/components/mode-toggle'
import { ThemeProvider } from '@/components/theme-provider'
import { HistoryTracker } from '@/components/history-tracker'

// const sans = localFont({
//   src: './_fonts/InterVariable.woff2',
//   preload: true,
//   variable: '--sans',
// })

// const serif = localFont({
//   src: './_fonts/LoraItalicVariable.woff2',
//   preload: true,
//   variable: '--serif',
// })

// const mono = localFont({
//   src: './_fonts/IosevkaFixedCurly-ExtendedMedium.woff2',
//   preload: true,
//   variable: '--mono',
// })

export const metadata: Metadata = {
  title: {
    template: '%s | Leo',
    default: 'Leo',
  },
}

export const viewport: Viewport = {
  maximumScale: 1,
  colorScheme: 'only light',
  themeColor: '#fcfcfc',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='overflow-x-hidden touch-manipulation' suppressHydrationWarning>
      <body
        className={cn(
          'font-mono',
          'w-full p-6 sm:p-10 md:p-14',
          'text-sm leading-6 sm:text-[15px] sm:leading-7 md:text-base md:leading-7',
          'text-rurikon-500',
          'antialiased',
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >   
          <div className='fixed sm:hidden h-6 sm:h-10 md:h-14 w-full top-0 left-0 z-30 pointer-events-none content-fade-out' />
          <div className=''>
            <div className='flex flex-col mobile:flex-row justify-center'>
              <Navbar />
              <main className='relative flex-1 max-w-2xl [contain:inline-size]'>
                <div className='absolute w-full h-px opacity-50 bg-rurikon-border dark:bg-rurikon-border-dark right-0 mobile:right-auto mobile:left-0 mobile:w-px mobile:h-full mobile:opacity-100' />
                <Provider>
                  <ViewTransition name='crossfade'>
                    <article className='pl-0 pt-6 mobile:pt-0 mobile:pl-6 sm:pl-10 md:pl-14'>
                    <HistoryTracker />
                      {children}
                    </article>
                  </ViewTransition>            
                </Provider>


              </main>
            </div>  
            
            <div className="fixed bottom-6 right-6 z-50">
                  <ModeToggle /> 
            </div>           
          </div>
      
        </ThemeProvider>

      </body>
    </html>
  )
}



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Provider } from "react-wrap-balancer";
// import { unstable_ViewTransition as ViewTransition } from 'react'
// import Navbar from "@/components/Navbar";
// import { Separator } from "@/components/ui/separator";
// import { ModeToggle } from "@/components/mode-toggle";
// import { ThemeProvider } from "@/components/theme-provider";
// import { HistoryTracker } from "@/components/history-tracker";
// import Footer from "@/components/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
        // <ThemeProvider
        //   attribute="class"
        //   defaultTheme="system"
        //   enableSystem
        //   disableTransitionOnChange
        // >  
//           <div className="md:hidden w-full pt-4 px-4 flex justify-end font-mono">
//             <Navbar orientation="horizontal" />
//           </div>
//           <div className="container flex font-mono justify-center pt-10 md:pt-18 gap-12">
//             <div className="hidden md:flex flex gap-10">
//               <Navbar />
//               <Separator orientation="vertical"/>        
//             </div>

            
//             <Provider>
//               <ViewTransition name="crossfade">
//                 <div className="mdx-container">
//                   <HistoryTracker />
//                   {children}
//                 </div>
//               </ViewTransition>        
//             </Provider> 
            // <div className="fixed bottom-6 right-6 z-50">
            //   <ModeToggle /> 
            // </div> 
                
//           </div>

//           <div>
//             <Footer />
//           </div>

//         </ThemeProvider>

//       </body>
//     </html>
//   );
// }
